interface Env {
	AI: Ai;
	UPSTASH_REDIS_REST_URL: string;
	UPSTASH_REDIS_REST_TOKEN: string;
	UPSTASH_REDIS_RATE_LIMIT_VIRGINIA_REST_URL: string;
	UPSTASH_REDIS_RATE_LIMIT_VIRGINIA_REST_TOKEN: string;
	UPSTASH_REDIS_RATE_LIMIT_CALIFORNIA_REST_URL: string;
	UPSTASH_REDIS_RATE_LIMIT_CALIFORNIA_REST_TOKEN: string;
	UPSTASH_REDIS_RATE_LIMIT_AUSTRALIA_REST_URL: string;
	UPSTASH_REDIS_RATE_LIMIT_AUSTRALIA_REST_TOKEN: string;
	UPSTASH_REDIS_RATE_LIMIT_BRAZIL_REST_URL: string;
	UPSTASH_REDIS_RATE_LIMIT_BRAZIL_REST_TOKEN: string;
	UPSTASH_REDIS_RATE_LIMIT_JAPAN_REST_URL: string;
	UPSTASH_REDIS_RATE_LIMIT_JAPAN_REST_TOKEN: string;
	UPSTASH_REDIS_RATE_LIMIT_GERMANY_REST_URL: string;
	UPSTASH_REDIS_RATE_LIMIT_GERMANY_REST_TOKEN: string;
	YOUTUBE_API_PASSKEY: string;
	YOUTUBE_API_ENDPOINT_URL: string;
	PUBLIC_API_KEY_V1: string;
  }
