#:schema node_modules/wrangler/config-schema.json
name = "quickskim-api"
main = "src/index.ts"
compatibility_date = "2024-12-16"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
invocation_logs = false

